/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUILogin.java
 *
 * Created on 08/02/2011, 09:20:02
 */

package cuLogin;

import java.awt.event.ActionListener;

/**
 *
 * @author franco
 */
public class GUILogin extends javax.swing.JFrame {

	  // Variables declaration - do not modify
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHerramientas;
    private javax.swing.JMenuItem jMenuItemAgregar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemVersion;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jnombreUsuario;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JLabel password;
    // End of variables declaration


    /** Creates new form GUILogin */
    public GUILogin(boolean modal) {
        super();
        initComponents();
        setTitle("Login Usuario");
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        nombreUsuario = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jnombreUsuario = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHerramientas = new javax.swing.JMenu();
        jMenuItemAgregar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombreUsuario.setText("Nombre Usuario: ");

        password.setText("Password: ");
      
        

        jButtonAceptar.setText("Aceptar");
      

        jButtonCancelar.setText("Cancelar");
       

        jMenuHerramientas.setText("Herramientas");

        jMenuItemAgregar.setText("Agregar Usuario");
        jMenuHerramientas.add(jMenuItemAgregar);
        jMenuHerramientas.add(jSeparator1);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuHerramientas.add(jMenuItemSalir);

        jMenuBar1.add(jMenuHerramientas);

        jMenuAyuda.setText("Ayuda");

        jMenuItemVersion.setText("Versión");
        jMenuAyuda.add(jMenuItemVersion);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(password))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpassword)
                            .addComponent(jnombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsuario)
                    .addComponent(jnombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar))
                .addGap(37, 37, 37))
        );
        setResizable(false);
        pack();
    }// </editor-fold>

   
   
	
	/**
	 * @return the jButtonAceptar
	 */
	public javax.swing.JButton getjButtonAceptar() {
		return jButtonAceptar;
	}

	/**
	 * @param jButtonAceptar the jButtonAceptar to set
	 */
	public void setjButtonAceptar(javax.swing.JButton jButtonAceptar) {
		this.jButtonAceptar = jButtonAceptar;
	}

	/**
	 * @return the jButtonCancelar
	 */
	public javax.swing.JButton getjButtonCancelar() {
		return jButtonCancelar;
	}

	/**
	 * @param jButtonCancelar the jButtonCancelar to set
	 */
	public void setjButtonCancelar(javax.swing.JButton jButtonCancelar) {
		this.jButtonCancelar = jButtonCancelar;
	}

	/**
	 * @return the jMenuAyuda
	 */
	public javax.swing.JMenu getjMenuAyuda() {
		return jMenuAyuda;
	}

	/**
	 * @param jMenuAyuda the jMenuAyuda to set
	 */
	public void setjMenuAyuda(javax.swing.JMenu jMenuAyuda) {
		this.jMenuAyuda = jMenuAyuda;
	}

	/**
	 * @return the jMenuBar1
	 */
	public javax.swing.JMenuBar getjMenuBar1() {
		return jMenuBar1;
	}

	/**
	 * @param jMenuBar1 the jMenuBar1 to set
	 */
	public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
		this.jMenuBar1 = jMenuBar1;
	}

	/**
	 * @return the jMenuHerramientas
	 */
	public javax.swing.JMenu getjMenuHerramientas() {
		return jMenuHerramientas;
	}

	/**
	 * @param jMenuHerramientas the jMenuHerramientas to set
	 */
	public void setjMenuHerramientas(javax.swing.JMenu jMenuHerramientas) {
		this.jMenuHerramientas = jMenuHerramientas;
	}

	/**
	 * @return the jMenuItemAgregar
	 */
	public javax.swing.JMenuItem getjMenuItemAgregar() {
		return jMenuItemAgregar;
	}

	/**
	 * @param jMenuItemAgregar the jMenuItemAgregar to set
	 */
	public void setjMenuItemAgregar(javax.swing.JMenuItem jMenuItemAgregar) {
		this.jMenuItemAgregar = jMenuItemAgregar;
	}

	/**
	 * @return the jMenuItemSalir
	 */
	public javax.swing.JMenuItem getjMenuItemSalir() {
		return jMenuItemSalir;
	}

	/**
	 * @param jMenuItemSalir the jMenuItemSalir to set
	 */
	public void setjMenuItemSalir(javax.swing.JMenuItem jMenuItemSalir) {
		this.jMenuItemSalir = jMenuItemSalir;
	}

	/**
	 * @return the jMenuItemVersion
	 */
	public javax.swing.JMenuItem getjMenuItemVersion() {
		return jMenuItemVersion;
	}

	/**
	 * @param jMenuItemVersion the jMenuItemVersion to set
	 */
	public void setjMenuItemVersion(javax.swing.JMenuItem jMenuItemVersion) {
		this.jMenuItemVersion = jMenuItemVersion;
	}

	/**
	 * @return the jnombreUsuario
	 */
	public javax.swing.JTextField getJnombreUsuario() {
		return jnombreUsuario;
	}

	/**
	 * @param jnombreUsuario the jnombreUsuario to set
	 */
	public void setJnombreUsuario(javax.swing.JTextField jnombreUsuario) {
		this.jnombreUsuario = jnombreUsuario;
	}

	/**
	 * @return the jpassword
	 */
	public javax.swing.JPasswordField getJpassword() {
		return jpassword;
	}

	/**
	 * @param jpassword the jpassword to set
	 */
	public void setJpassword(javax.swing.JPasswordField jpassword) {
		this.jpassword = jpassword;
	}

	/**
	 * @return the nombreUsuario
	 */
	public javax.swing.JLabel getNombreUsuario() {
		return nombreUsuario;
	}

	/**
	 * @param nombreUsuario the nombreUsuario to set
	 */
	public void setNombreUsuario(javax.swing.JLabel nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	/**
	 * @return the password
	 */
	public javax.swing.JLabel getPassword() {
		return password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(javax.swing.JLabel password) {
		this.password = password;
	}

	/**
	 * Metodo que permite escuchar los botoner aceptar y cancelar.
	 *
	 *@param lis actionEvent asignado a los botones.
	 */
	public void setListenerButtons(ActionListener lis){
		this.jButtonAceptar.addActionListener(lis);
		this.jButtonCancelar.addActionListener(lis);
		this.jMenuItemSalir.addActionListener(lis);
	}
}
