/**
 * 
 */
package cuGestionarUbicacion;

import java.awt.event.ActionListener;

import persistencia.domain.Ubicacion;

/**
 * Clase GUI que reprensenta la ventana para una ubicacion.
 * @author TesisGeologia.
 *
 */
public class GUIUbicacion extends javax.swing.JDialog {
	
	// Variables declaration - do not modify
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonAceptar;private javax.swing.JComboBox jComboBoxProvincia;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelLatitud;
    private javax.swing.JLabel jLabelLongitud;
    private javax.swing.JLabel jLabelNombreUbicacion;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuVersion;
    private javax.swing.JMenuItem jMenuItemAgregar;
    private javax.swing.JMenuItem jMenuItemCancelar;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldLongitud;
    private javax.swing.JTextField jTextFieldLatitud;
    private javax.swing.JTextField jTextFieldNombreUbicacion;
    // End of variables declaration

    /** Creates new form GUIUbicacion */
    public GUIUbicacion() {
    	super();
        setModal(true);
        setResizable(false);
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldNombreUbicacion = new javax.swing.JTextField();
        jTextFieldLongitud = new javax.swing.JTextField();
        jTextFieldLatitud = new javax.swing.JTextField();
        initComponents();
    }
    
    /** Creates new form GUIUbicacion */
    public GUIUbicacion(Ubicacion ubicacion) {
    	super();
        setModal(true);
        setResizable(false);
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldNombreUbicacion = new javax.swing.JTextField();
        jTextFieldLongitud = new javax.swing.JTextField();
        jTextFieldLatitud = new javax.swing.JTextField();
        jTextFieldCiudad.setText(ubicacion.getCiudad());
        jTextFieldNombreUbicacion.setText(ubicacion.getNombreUbicacion());
        jTextFieldLongitud.setText(ubicacion.getLongitud().toString());
        jTextFieldLatitud.setText(ubicacion.getLatitud().toString());
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelNombreUbicacion = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelLatitud = new javax.swing.JLabel();
        jLabelLongitud = new javax.swing.JLabel();
        jComboBoxProvincia = new javax.swing.JComboBox();
        jLabelProvincia = new javax.swing.JLabel();
        
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAgregar = new javax.swing.JMenuItem();
        jMenuItemCancelar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAceptar.setText("Agregar");

        jButtonCancelar.setText("Cancelar");

        jLabelNombreUbicacion.setText("(*) Nombre Ubicación :");

        jLabelCiudad.setText("(*) Ciudad:");

        jLabelLatitud.setText("Latitud:");

        jLabelLongitud.setText("Longitud:");

        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buenos Aires", "Catamarca", "Chaco", "Chubut", "Capital Federal", "Cordoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquen", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago Del Estero", "Tierra Del Fuego", "Tucuman" }));

        jLabelProvincia.setText("Provincia:");

        jMenu1.setText("Herramientas");

        jMenuItemAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        jMenuItemAgregar.setText("Agregar");
        jMenu1.add(jMenuItemAgregar);

        jMenuItemCancelar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemCancelar.setText("Cancelar");
        jMenu1.add(jMenuItemCancelar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuVersion.setText("Versión");
        jMenu2.add(jMenuVersion);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelProvincia)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxProvincia, 0, 168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jButtonAceptar))
                            .addComponent(jLabelNombreUbicacion)
                            .addComponent(jLabelLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLatitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldLongitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTextFieldLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>
    
    /**
	 * Metodo que permite escuchar los botones y los item
	 * del menu.
	 *
	 *@param lis actionEvent asignado a los botones.
	 */
	public void setListenerButtons(ActionListener lis){
		this.jButtonAceptar.addActionListener(lis);
		this.jButtonCancelar.addActionListener(lis);
		this.jMenuItemAgregar.addActionListener(lis);
		this.jMenuItemCancelar.addActionListener(lis);
		this.jMenuVersion.addActionListener(lis);
	}
	
	public String[] getData() {
		String[] data = new String[5];
		data[0]= jComboBoxProvincia.getSelectedItem().toString();
		data[1]= jTextFieldCiudad.getText();
		data[2]= jTextFieldNombreUbicacion.getText();
		data[3]= jTextFieldLongitud.getText();
		data[4]= jTextFieldLatitud.getText();
		return data;
	}


    /**
	 * @return the jButtonCancelar
	 */
	public javax.swing.JButton getjButtonCancelar() {
		return jButtonCancelar;
	}

	/**
	 * @return the jButtonAceptar
	 */
	public javax.swing.JButton getjButtonAceptar() {
		return jButtonAceptar;
	}

	/**
	 * @return the jComboBoxProvincia
	 */
	public javax.swing.JComboBox getjComboBoxProvincia() {
		return jComboBoxProvincia;
	}

	/**
	 * @return the jMenuVersion
	 */
	public javax.swing.JMenuItem getjMenuVersion() {
		return jMenuVersion;
	}

	/**
	 * @return the jMenuItemAgregar
	 */
	public javax.swing.JMenuItem getjMenuItemAgregar() {
		return jMenuItemAgregar;
	}

	/**
	 * @return the jMenuItemCancelar
	 */
	public javax.swing.JMenuItem getjMenuItemCancelar() {
		return jMenuItemCancelar;
	}

	/**
	 * @return the jTextFieldCiudad
	 */
	public javax.swing.JTextField getjTextFieldCiudad() {
		return jTextFieldCiudad;
	}

	/**
	 * @return the jTextFieldLongitud
	 */
	public javax.swing.JTextField getjTextFieldLongitud() {
		return jTextFieldLongitud;
	}

	/**
	 * @return the jTextFieldLatitud
	 */
	public javax.swing.JTextField getjTextFieldLatitud() {
		return jTextFieldLatitud;
	}

	/**
	 * @return the jTextFieldNombreUbicacion
	 */
	public javax.swing.JTextField getjTextFieldNombreUbicacion() {
		return jTextFieldNombreUbicacion;
	}

	
}
